FROM mysql:5.7

LABEL maintainer="matheus.demiro"

ADD /src/scripts/init-db.sql /docker-entrypoint-initdb.d/init-db.sql

RUN mkdir mysql
WORKDIR /mysql

EXPOSE 3307

# ADD ./src/scripts/start-db.sh /mysql/docker-entrypoint-initdb.d/
# RUN /mysql/docker-entrypoint-initdb.d/init_db.sh